# Base ERPNext image
FROM frappe/erpnext:latest

WORKDIR /home/frappe/frappe-bench

# Declare build arguments
ARG SITE_NAME
ARG ADMIN_PASSWORD
ARG DB_ROOT_PASSWORD
ARG MIGRATE
ARG ENABLE_DB
ARG DB_HOST
ARG CREATE_SITE
ARG CONFIGURE
ARG REGENERATE_APPS_TXT
ARG INSTALL_APP_ARGS
ARG IMAGE_NAME
ARG VERSION
ARG FRAPPE_SITE_NAME_HEADER
 


# Set environment variables for build
ENV SITE_NAME=${SITE_NAME}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}
ENV DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
ENV MIGRATE=${MIGRATE}
ENV ENABLE_DB=${ENABLE_DB}
ENV DB_HOST=${DB_HOST}
ENV CREATE_SITE=${CREATE_SITE}
ENV CONFIGURE=${CONFIGURE}
ENV REGENERATE_APPS_TXT=${REGENERATE_APPS_TXT}
ENV INSTALL_APP_ARGS=${INSTALL_APP_ARGS}
ENV IMAGE_NAME=${IMAGE_NAME}
ENV VERSION=${VERSION}
ENV FRAPPE_SITE_NAME_HEADER=${FRAPPE_SITE_NAME_HEADER}



# Install missing Python dependencies
RUN /home/frappe/frappe-bench/env/bin/pip install bleach

# Install assist
RUN bench get-app git clone https://github.com/samletnorge/assist.git --branch main
